Add Hubspot authorise URL
this-andy/thiscovery_admin pull request #34
Opened 2022-01-13 15:32 UTC by sophiemachin

2022-01-14 13:44 UTC, afs25 requested changes

2022-01-14 13:44 UTC, afs25 commented on thiscovery_admin/templates/hubspot.html
> +        <a href="https://app.hubspot.com/oauth/authorize?client_id={{ client_id }}&redirect_uri=https://abcd-123-45-88-14.ngrok.io/hubspot&scope=contacts%20timeline" target="_blank">Authorise</a>
I don't like that the variable bit abcd-123-45-88-14 in this URL is hardcoded. Can we implement a better solution? I know that thiscovery_admin doesn't have a dev_config file, but getting the settings file in use to export to os.env and then reading the value would work. Let's discuss this at the next dev meeting.

2022-01-20 15:38 UTC, sophiemachin commented on thiscovery_admin/templates/hubspot.html
> +        <a href="https://app.hubspot.com/oauth/authorize?client_id={{ client_id }}&redirect_uri=https://abcd-123-45-88-14.ngrok.io/hubspot&scope=contacts%20timeline" target="_blank">Authorise</a>
Apologies I've only just seen this message. I'll have a go at your suggestion.

2022-01-20 16:16 UTC, sophiemachin commented on thiscovery_admin/templates/hubspot.html
> +        <a href="https://app.hubspot.com/oauth/authorize?client_id={{ client_id }}&redirect_uri=https://abcd-123-45-88-14.ngrok.io/hubspot&scope=contacts%20timeline" target="_blank">Authorise</a>
@afs25  I've made that change

2022-01-20 19:27 UTC, sophiemachin commented on thiscovery_admin/projects/views.py
> +        "ngrok_address": os.environ.get("NGROK_ADDRESS", ""),
I've added a message

2022-01-21 08:13 UTC, afs25 approved these changes

2022-01-21 09:20 UTC, merged